name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
      - 'refactoring'
  - title: 'ğŸ› Hotfixes'
    label: 'hotfix'
  - title: 'ETC'
    label: 'doc'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Changes

  $CHANGES